import turtle
t = turtle.Turtle()
t.speed(3)
#틀
t.penup()
t.forward(360)
t.pendown()
t.left(90)
t.forward(240)
t.left(90)
t.forward(720)
t.left(90)
t.forward(480)
t.left(90)
t.forward(720)
t.left(90)
t.forward(240)
t.right(90)

#태극
t.penup()
t.goto(0,-120)
t.pendown()
t.circle(120) 
t.fillcolor("red")
t.circle(120,270)
t.circle(120, -33.69)
t.circle(60,180)
t.begin_fill()
t.circle(60,-180)
t.circle(120,-180)
t.end_fill()

t.fillcolor("blue")
t.begin_fill()
t.circle(60,180)
t.end_fill()
t.begin_fill()
t.circle(60,-180)
t.circle(120,-180)
t.end_fill()

t.fillcolor("red")
t.circle(60,180)
t.begin_fill()
t.circle(60,-180)
t.end_fill()


#4괘로 이동
t.penup()
t.goto(0,0)
t.left(33.69)
t.forward(60)
t.right(90)
t.forward(200)

#4
t.left(33.69)
t.pendown()
t.fillcolor("black")
t.begin_fill()
for i in range(2):
    t.left(90)
    t.forward(120)
    t.left(90)
    t.forward(20)
t.end_fill()

t.penup()
t.forward(10)
t.pendown()
t.begin_fill()
for i in range(2):
        t.forward(20)
        t.left(90)
        t.forward(55)
        t.left(90)
t.end_fill()
t.forward(20)
t.left(90)
t.penup()
t.forward(65)
t.pendown()
t.begin_fill()
for i in range(2):
        t.forward(55)
        t.left(90)
        t.forward(20)
        t.left(90)
t.end_fill()
t.penup()
t.right(180)
t.forward(65)
t.left(90)
t.forward(10)
t.pendown()

t.begin_fill()
for i in range(2):
        t.forward(20)
        t.left(90)
        t.forward(120)
        t.left(90)
t.end_fill()

#5
t.right(180)
t.penup()
t.forward(500)
t.pendown()
t.begin_fill()
for i in range(2):
    t.right(90)
    t.forward(55)
    t.right(90)
    t.forward(20)
t.end_fill()
t.right(90)
t.penup()
t.forward(65)
t.pendown()
t.begin_fill()
for i in range(2):
    t.forward(55)
    t.right(90)
    t.forward(20)
    t.right(90)
t.end_fill()
t.right(180)
t.penup()
t.forward(65)
t.left(90)
t.forward(30)
t.pendown()
t.left(90)
t.begin_fill()
for i in range(2):
    t.forward(120)
    t.right(90)
    t.forward(20)
    t.right(90)
t.end_fill()
t.right(90)
t.penup()
t.forward(30)
t.pendown()
t.left(90)
t.begin_fill()
for i in range(2):
    t.forward(55)
    t.right(90)
    t.forward(20)
    t.right(90)
t.end_fill()
t.penup()
t.forward(65)
t.pendown()
t.begin_fill()
for i in range(2):
    t.forward(55)
    t.right(90)
    t.forward(20)
    t.right(90)
t.end_fill()
t.right(180)
t.penup()
t.forward(65)
t.left(90)
t.goto(0,0)
t.left(90-33.69)
t.forward(60)
t.left(90)
t.forward(200)

t.right(33.69)
t.right(90)

#6
t.begin_fill()
for i in range(2):
    t.forward(55)
    t.right(90)
    t.forward(20)
    t.right(90)
t.end_fill()


t.penup()
t.forward(65)
t.pendown()
t.begin_fill()
for i in range(2):
    t.forward(55)
    t.right(90)
    t.forward(20)
    t.right(90)
t.end_fill()
t.penup()
t.right(180)
t.forward(65)
t.right(90)

for i in range(2):
    t.forward(30)
    t.begin_fill()
    for j in range(2):
        t.right(90)
        t.forward(55)
        t.right(90)
        t.forward(20)
    t.end_fill()
    t.right(90)
    t.penup()
    t.forward(65)
    t.pendown()
    t.begin_fill()
    for i in range(2):
        t.forward(55)
        t.right(90)
        t.forward(20)
        t.right(90)
    t.end_fill()
    t.penup()
    t.right(180)
    t.forward(65)
    t.right(90)

#3
t.right(180)
t.penup()
t.forward(430)
t.pendown()
for i in range(3):
    t.penup()
    t.forward(30)
    t.pendown()
    t.begin_fill()
    for j in range(2):
        t.left(90)
        t.forward(120)
        t.left(90)
        t.forward(20)
    t.end_fill()
t.hideturtle()


